-- Auto-generated by backend/sql/build-schema.mjs — do not hand-edit.
-- Source: the 39 historical Supabase migration files, with
-- Supabase-only constructs (RLS policies, storage.* schema, the auth.users
-- admin-bootstrap trigger, has_role()/handle_new_user_role()) stripped, and
-- authorization moved to backend middleware instead (see src/middleware/auth.ts).

create extension if not exists pgcrypto;

-- Replaces Supabase's internal auth.users table. Populated by the Google
-- OAuth callback (src/routes/auth.ts), not by these migrations.
create table if not exists public.users (
  id uuid primary key default gen_random_uuid(),
  google_sub text not null unique,
  email text not null,
  name text,
  avatar_url text,
  created_at timestamptz not null default now()
);

-- Backend-managed session store, replaces Supabase Auth's session handling.
create table if not exists public.admin_sessions (
  id text primary key,
  user_id uuid not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null
);


-- ==== 20260504005916_6da44c1a-fa17-4cf9-925c-a459092db20b.sql ====

-- Roles
create type public.app_role as enum ('admin', 'user');


create table public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.users(id) on delete cascade,
  role public.app_role not null,
  created_at timestamptz not null default now(),
  unique(user_id, role)
);


-- updated_at helper
create or replace function public.set_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end;
$$;


-- site_settings (single row)
create table public.site_settings (
  id uuid primary key default gen_random_uuid(),
  site_name text not null default 'Mi Tienda',
  logo_url text,
  phone text,
  email text,
  whatsapp text,
  instagram_url text,
  facebook_url text,
  address text,
  updated_at timestamptz not null default now()
);

create trigger site_settings_updated_at before update on public.site_settings
  for each row execute function public.set_updated_at();


-- banners
create table public.banners (
  id uuid primary key default gen_random_uuid(),
  title text not null default '',
  subtitle text default '',
  cta_text text default '',
  cta_href text default '/',
  image_url text,
  bg_color text default '#0ea5e9',
  sort_order int not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger banners_updated_at before update on public.banners for each row execute function public.set_updated_at();


-- categories
create table public.categories (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text default '',
  image_url text,
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger categories_updated_at before update on public.categories for each row execute function public.set_updated_at();


-- products
create table public.products (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  description text default '',
  price numeric(12,2) not null default 0,
  category_id uuid references public.categories(id) on delete set null,
  stock int not null default 0,
  featured boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger products_updated_at before update on public.products for each row execute function public.set_updated_at();

create index products_category_idx on public.products(category_id);


-- product images
create table public.product_images (
  id uuid primary key default gen_random_uuid(),
  product_id uuid not null references public.products(id) on delete cascade,
  url text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index product_images_product_idx on public.product_images(product_id);

-- ==== 20260504005945_c862015b-acbb-49a8-91f1-c0d9522aa67d.sql ====


-- Fix search_path for set_updated_at
create or replace function public.set_updated_at()
returns trigger language plpgsql
set search_path = public
as $$ begin new.updated_at = now(); return new; end; $$;

-- ==== 20260504014855_a34b4b4e-e861-4b29-9c9e-1cefa5ed645b.sql ====
CREATE TABLE public.product_packs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  units integer NOT NULL,
  price numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);


CREATE INDEX idx_product_packs_product ON public.product_packs(product_id);

-- ==== 20260504015646_8437cb2c-7393-4ac7-9482-43d429a336df.sql ====
ALTER TABLE public.product_packs ADD COLUMN IF NOT EXISTS label text;

ALTER TABLE public.product_packs ALTER COLUMN units DROP NOT NULL;

-- ==== 20260504215612_cc2128bd-b8df-4e74-9d37-6fc7bdb99eb9.sql ====
-- Add photos_required to product variants (per pack/measure)
ALTER TABLE public.product_packs
  ADD COLUMN IF NOT EXISTS photos_required integer;

-- ==== 20260505014651_4745a23f-c6e9-4077-af8c-95ce5e2beb4f.sql ====

-- Enums
CREATE TYPE public.sale_status AS ENUM ('pendiente','confirmada','enviada','entregada','cancelada');

CREATE TYPE public.sale_source AS ENUM ('admin','public');


-- Customers
CREATE TABLE public.customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  phone text,
  email text,
  address text,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER customers_updated_at BEFORE UPDATE ON public.customers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Payment methods
CREATE TABLE public.payment_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  surcharge_pct numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER payment_methods_updated_at BEFORE UPDATE ON public.payment_methods FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Shipping methods
CREATE TABLE public.shipping_methods (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  cost numeric NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER shipping_methods_updated_at BEFORE UPDATE ON public.shipping_methods FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Sales
CREATE TABLE public.sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_id uuid REFERENCES public.customers(id) ON DELETE SET NULL,
  payment_method_id uuid REFERENCES public.payment_methods(id) ON DELETE SET NULL,
  shipping_method_id uuid REFERENCES public.shipping_methods(id) ON DELETE SET NULL,
  subtotal numeric NOT NULL DEFAULT 0,
  shipping_cost numeric NOT NULL DEFAULT 0,
  surcharge numeric NOT NULL DEFAULT 0,
  total numeric NOT NULL DEFAULT 0,
  status public.sale_status NOT NULL DEFAULT 'pendiente',
  source public.sale_source NOT NULL DEFAULT 'admin',
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER sales_updated_at BEFORE UPDATE ON public.sales FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE INDEX idx_sales_created_at ON public.sales(created_at DESC);

CREATE INDEX idx_sales_status ON public.sales(status);


-- Sale items
CREATE TABLE public.sale_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_id uuid NOT NULL REFERENCES public.sales(id) ON DELETE CASCADE,
  product_id uuid REFERENCES public.products(id) ON DELETE SET NULL,
  product_name text NOT NULL,
  unit_price numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  subtotal numeric NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sale_items_sale_id ON public.sale_items(sale_id);

-- ==== 20260505020049_f2e79025-3bd6-4554-a4a0-3b095b4d5f11.sql ====

-- Products & packs: sale fields
ALTER TABLE public.products
  ADD COLUMN compare_at_price numeric,
  ADD COLUMN sale_starts_at timestamptz,
  ADD COLUMN sale_ends_at timestamptz;


ALTER TABLE public.product_packs
  ADD COLUMN compare_at_price numeric,
  ADD COLUMN sale_starts_at timestamptz,
  ADD COLUMN sale_ends_at timestamptz;


-- Sales: coupon usage
ALTER TABLE public.sales
  ADD COLUMN coupon_code text,
  ADD COLUMN discount_amount numeric NOT NULL DEFAULT 0;


-- Coupons
CREATE TYPE public.discount_type AS ENUM ('percentage', 'fixed');


CREATE TABLE public.coupons (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code text NOT NULL UNIQUE,
  discount_type public.discount_type NOT NULL DEFAULT 'percentage',
  discount_value numeric NOT NULL DEFAULT 0,
  min_order_total numeric,
  starts_at timestamptz,
  ends_at timestamptz,
  usage_limit integer,
  times_used integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


-- Allow public to increment times_used when applying a coupon during checkout.
-- Restricted via a SECURITY DEFINER function (no direct UPDATE policy needed).
CREATE OR REPLACE FUNCTION public.apply_coupon(_code text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.coupons
  SET times_used = times_used + 1
  WHERE upper(code) = upper(_code)
    AND active = true
    AND (starts_at IS NULL OR starts_at <= now())
    AND (ends_at IS NULL OR ends_at >= now())
    AND (usage_limit IS NULL OR times_used < usage_limit);
END;
$$;


CREATE TRIGGER coupons_updated_at BEFORE UPDATE ON public.coupons
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ==== 20260505022825_552cf5fd-9f37-4933-97be-b0e1707bd7e2.sql ====

ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS mp_preference_id text,
  ADD COLUMN IF NOT EXISTS mp_payment_id text,
  ADD COLUMN IF NOT EXISTS mp_status text;


ALTER TABLE public.payment_methods
  ADD COLUMN IF NOT EXISTS provider text NOT NULL DEFAULT 'manual';

-- ==== 20260505024431_95a77053-1ecd-48d7-af7e-5189b14504d8.sql ====

CREATE SEQUENCE IF NOT EXISTS public.sales_order_number_seq START WITH 1000 INCREMENT BY 1;


ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS order_number INTEGER UNIQUE;


-- Backfill existing rows in created_at order
WITH ordered AS (
  SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) + 999 AS n
  FROM public.sales
  WHERE order_number IS NULL
)
UPDATE public.sales s SET order_number = o.n FROM ordered o WHERE s.id = o.id;


-- Advance sequence past current max
SELECT setval('public.sales_order_number_seq', GREATEST(1000, COALESCE((SELECT MAX(order_number) FROM public.sales), 999)) + 1, false);


ALTER TABLE public.sales ALTER COLUMN order_number SET DEFAULT nextval('public.sales_order_number_seq');

ALTER TABLE public.sales ALTER COLUMN order_number SET NOT NULL;

ALTER SEQUENCE public.sales_order_number_seq OWNED BY public.sales.order_number;

-- ==== 20260508154510_559faabc-c514-4898-a00a-19e4d519cdc2.sql ====

ALTER TABLE public.product_images
  ADD COLUMN IF NOT EXISTS focal_x numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS focal_y numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS zoom numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fit text NOT NULL DEFAULT 'cover';


ALTER TABLE public.banners
  ADD COLUMN IF NOT EXISTS focal_x numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS focal_y numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS zoom numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fit text NOT NULL DEFAULT 'cover',
  ADD COLUMN IF NOT EXISTS hide_text_mobile boolean NOT NULL DEFAULT false;

-- ==== 20260512170446_f02f51b0-b237-444e-9c6d-0221f178cc79.sql ====

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS weight_kg numeric NOT NULL DEFAULT 0.5,
  ADD COLUMN IF NOT EXISTS length_cm numeric NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS width_cm numeric NOT NULL DEFAULT 10,
  ADD COLUMN IF NOT EXISTS height_cm numeric NOT NULL DEFAULT 10;


ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS shipping_postal_code text,
  ADD COLUMN IF NOT EXISTS shipping_address_extra text,
  ADD COLUMN IF NOT EXISTS andreani_branch_id text,
  ADD COLUMN IF NOT EXISTS andreani_tracking_number text,
  ADD COLUMN IF NOT EXISTS andreani_label_url text,
  ADD COLUMN IF NOT EXISTS andreani_status text;


ALTER TABLE public.shipping_methods
  ADD COLUMN IF NOT EXISTS provider text NOT NULL DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS tipo text;

-- ==== 20260512184639_4692c2eb-c353-4ce8-804c-9ea4e0d5fdeb.sql ====
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS product_type text NOT NULL DEFAULT 'standard';


CREATE TABLE public.product_sticker_folders (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  slug text,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


CREATE TABLE public.product_stickers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL REFERENCES public.product_sticker_folders(id) ON DELETE CASCADE,
  name text NOT NULL,
  image_url text,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


CREATE INDEX idx_sticker_folders_product ON public.product_sticker_folders(product_id);

CREATE INDEX idx_stickers_folder ON public.product_stickers(folder_id);


CREATE TRIGGER trg_sticker_folders_updated BEFORE UPDATE ON public.product_sticker_folders FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_stickers_updated BEFORE UPDATE ON public.product_stickers FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ==== 20260512185928_4c73894e-19f5-408f-b849-192c6fa8484b.sql ====
ALTER TABLE public.product_sticker_folders
  ADD CONSTRAINT product_sticker_folders_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;

-- ==== 20260513224338_26ed24a4-67d9-45f1-9eee-222d43ad3d8d.sql ====

ALTER TABLE public.shipping_methods
  ADD COLUMN IF NOT EXISTS enviopack_carrier text,
  ADD COLUMN IF NOT EXISTS enviopack_modalidad text,
  ADD COLUMN IF NOT EXISTS enviopack_servicio text DEFAULT 'N';


ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS enviopack_shipment_id text,
  ADD COLUMN IF NOT EXISTS shipping_province text,
  ADD COLUMN IF NOT EXISTS shipping_locality text,
  ADD COLUMN IF NOT EXISTS shipping_branch_id text;

-- ==== 20260527180048_82d2b689-6fcd-4709-9cc2-26cf4df4dd2f.sql ====

-- Limpieza Enviopack (no se usa)
ALTER TABLE public.shipping_methods 
  DROP COLUMN IF EXISTS enviopack_carrier,
  DROP COLUMN IF EXISTS enviopack_modalidad,
  DROP COLUMN IF EXISTS enviopack_servicio;


ALTER TABLE public.sales DROP COLUMN IF EXISTS enviopack_shipment_id;


-- Modo de cálculo de tarifa
ALTER TABLE public.shipping_methods 
  ADD COLUMN IF NOT EXISTS rate_mode text NOT NULL DEFAULT 'fixed';

-- valores válidos: 'fixed', 'andreani_api', 'manual_table'

-- CP de origen del comercio (para cotizar)
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS shipping_origin_postal_code text;


-- Tabla de tarifas manuales
CREATE TABLE IF NOT EXISTS public.shipping_rates (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shipping_method_id uuid NOT NULL REFERENCES public.shipping_methods(id) ON DELETE CASCADE,
  province text,
  postal_code_from text,
  postal_code_to text,
  cost numeric NOT NULL DEFAULT 0,
  free_from_amount numeric,
  active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


CREATE TRIGGER set_shipping_rates_updated_at
  BEFORE UPDATE ON public.shipping_rates
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE INDEX IF NOT EXISTS idx_shipping_rates_method ON public.shipping_rates(shipping_method_id);

-- ==== 20260527200623_9a816da0-8bd5-4263-9c52-9c13fd38c158.sql ====

-- Add columns to shipping_methods
ALTER TABLE public.shipping_methods
  ADD COLUMN IF NOT EXISTS delivery_type text NOT NULL DEFAULT 'domicilio',
  ADD COLUMN IF NOT EXISTS estimated_time text,
  ADD COLUMN IF NOT EXISTS pickup_hours text;


-- Add column to sales
ALTER TABLE public.sales
  ADD COLUMN IF NOT EXISTS shipping_branch_name text;


-- Free shipping rules
CREATE TABLE IF NOT EXISTS public.free_shipping_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shipping_method_id uuid REFERENCES public.shipping_methods(id) ON DELETE CASCADE,
  min_amount numeric NOT NULL DEFAULT 0,
  province text,
  postal_code_from text,
  postal_code_to text,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


CREATE TRIGGER set_updated_at_free_shipping_rules
  BEFORE UPDATE ON public.free_shipping_rules
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Local delivery zones
CREATE TABLE IF NOT EXISTS public.local_delivery_zones (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  shipping_method_id uuid NOT NULL REFERENCES public.shipping_methods(id) ON DELETE CASCADE,
  name text NOT NULL,
  postal_codes text[] NOT NULL DEFAULT '{}',
  cost numeric NOT NULL DEFAULT 0,
  estimated_time text,
  active boolean NOT NULL DEFAULT true,
  sort_order int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);


CREATE TRIGGER set_updated_at_local_delivery_zones
  BEFORE UPDATE ON public.local_delivery_zones
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ==== 20260531223846_262c1a81-9b00-4905-bf74-d8c3bccefdc7.sql ====

-- Materials
CREATE TABLE public.sticker_materials (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  base_price numeric NOT NULL DEFAULT 0,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_sticker_materials BEFORE UPDATE ON public.sticker_materials FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Finishes
CREATE TABLE public.sticker_finishes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  surcharge numeric NOT NULL DEFAULT 0,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_sticker_finishes BEFORE UPDATE ON public.sticker_finishes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Shapes
CREATE TABLE public.sticker_shapes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  icon text,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_sticker_shapes BEFORE UPDATE ON public.sticker_shapes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Sizes
CREATE TABLE public.sticker_sizes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  label text NOT NULL,
  width_cm numeric NOT NULL DEFAULT 0,
  height_cm numeric NOT NULL DEFAULT 0,
  price_multiplier numeric NOT NULL DEFAULT 1,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_sticker_sizes BEFORE UPDATE ON public.sticker_sizes FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Quantities
CREATE TABLE public.sticker_quantities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  quantity int NOT NULL,
  discount_pct numeric NOT NULL DEFAULT 0,
  sort_order int NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_sticker_quantities BEFORE UPDATE ON public.sticker_quantities FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


-- Sale items field for custom sticker config
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS custom_sticker_config jsonb;

-- ==== 20260604172631_83733f11-6d37-4633-a17b-64b05e2a67db.sql ====

CREATE TABLE public.product_addon_groups (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id uuid NOT NULL,
  name text NOT NULL,
  required boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_product_addon_groups
  BEFORE UPDATE ON public.product_addon_groups
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


CREATE TABLE public.product_addon_options (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  group_id uuid NOT NULL,
  name text NOT NULL,
  extra_price numeric NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER set_updated_at_product_addon_options
  BEFORE UPDATE ON public.product_addon_options
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();


ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS addons jsonb;

-- ==== 20260604173151_8c8a7b57-e956-4327-afa9-ec82a8b9052c.sql ====

ALTER TABLE public.product_addon_groups
  ADD CONSTRAINT product_addon_groups_product_id_fkey
  FOREIGN KEY (product_id) REFERENCES public.products(id) ON DELETE CASCADE;


ALTER TABLE public.product_addon_options
  ADD CONSTRAINT product_addon_options_group_id_fkey
  FOREIGN KEY (group_id) REFERENCES public.product_addon_groups(id) ON DELETE CASCADE;

-- ==== 20260626012450_f5e82f63-0113-4f86-9fb5-4f274c44322f.sql ====

ALTER TABLE public.product_addon_groups ADD COLUMN IF NOT EXISTS per_unit boolean NOT NULL DEFAULT false;

-- ==== 20260626014555_d76f04de-b30c-4d10-ae6f-79df6fc916b5.sql ====
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS about_content TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS info_content TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS info_faqs JSONB DEFAULT '[]'::jsonb;


CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SET search_path = public;


DROP TRIGGER IF EXISTS update_site_settings_updated_at ON public.site_settings;

CREATE TRIGGER update_site_settings_updated_at
  BEFORE UPDATE ON public.site_settings
  FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ==== 20260626015558_86ae7ac9-e842-4d94-aa79-fcfc1783cbaa.sql ====
ALTER TYPE sale_status ADD VALUE IF NOT EXISTS 'abonado';

-- ==== 20260626020549_45142ff2-5a95-4bf0-96f2-dd5a5e38828c.sql ====
ALTER TABLE public.sales ADD COLUMN IF NOT EXISTS tracking_code text, ADD COLUMN IF NOT EXISTS tracking_carrier text;

-- ==== 20260628150107_d9e782dd-715a-4890-a6fa-cacd0c472c51.sql ====
ALTER TABLE public.site_settings ADD COLUMN IF NOT EXISTS admin_notify_email text;

-- ==== 20260710160454_35ac6900-690c-4ced-b594-d0a6d4c984f4.sql ====
ALTER TABLE public.sale_items ADD COLUMN IF NOT EXISTS photos jsonb;

-- ==== 20260714021128_462fd7fb-ba88-42b1-91f1-66248928b3ed.sql ====
ALTER TABLE public.site_settings
  ADD COLUMN IF NOT EXISTS transfer_alias text,
  ADD COLUMN IF NOT EXISTS transfer_holder text,
  ADD COLUMN IF NOT EXISTS transfer_cbu text,
  ADD COLUMN IF NOT EXISTS transfer_bank text,
  ADD COLUMN IF NOT EXISTS transfer_notes text;

-- ==== 20260731200707_d1d70110-75a4-4aa2-ad5b-2b55eae5e185.sql ====
ALTER TABLE public.product_addon_groups ADD COLUMN IF NOT EXISTS is_multiplier boolean NOT NULL DEFAULT false;

ALTER TABLE public.product_addon_options ADD COLUMN IF NOT EXISTS price_multiplier numeric NOT NULL DEFAULT 1;

-- ==== 20260803161305_bc0cf042-3ffe-4c8a-9e61-93a791b0e15f.sql ====


CREATE OR REPLACE VIEW public.site_settings_public
WITH (security_invoker = off) AS
SELECT id, site_name, logo_url, phone, email, whatsapp, instagram_url, facebook_url,
       address, updated_at, shipping_origin_postal_code, about_content, info_content, info_faqs
FROM public.site_settings;

-- ==== 20260803161330_b9cf1d45-ed94-425b-9a11-74203d318cbc.sql ====

CREATE OR REPLACE VIEW public.site_settings_public
WITH (security_invoker = on) AS
SELECT id, site_name, logo_url, phone, email, whatsapp, instagram_url, facebook_url,
       address, updated_at, shipping_origin_postal_code, about_content, info_content, info_faqs
FROM public.site_settings;
