
ALTER TABLE public.product_images
  ADD COLUMN IF NOT EXISTS focal_x numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS focal_y numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS zoom numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fit text NOT NULL DEFAULT 'cover';

ALTER TABLE public.banners
  ADD COLUMN IF NOT EXISTS focal_x numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS focal_y numeric NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS zoom numeric NOT NULL DEFAULT 1,
  ADD COLUMN IF NOT EXISTS fit text NOT NULL DEFAULT 'cover',
  ADD COLUMN IF NOT EXISTS hide_text_mobile boolean NOT NULL DEFAULT false;
